---
- name: Gather some nextcloud configuration facts
  ansible.builtin.import_tasks: nc_facts.yml
  tags:
    - always
    - facts
- name: Set archive name
  ansible.builtin.set_fact:
    nc_archive_path: "{{ nextcloud_backup_target_dir }}/{{ nc_archive_name }}"
  tags:
    - always
- name: Enter maintenance mode
  nextcloud.admin.run_occ:
    nextcloud_path: "{{ nextcloud_webroot }}"
    command: maintenance:mode --on"
  become: true
  register: __goto_maintenance
  changed_when:
    - __goto_maintenance.stdout | regex_search('already') == none
  tags:
    - always

- name: Run basic backup
  ansible.legacy.import_tasks: files.yml
- name: Run users data backup
  ansible.legacy.import_tasks: user_data.yml
  when: nextcloud_backup_user
- name: Run applications backups
  ansible.legacy.import_tasks: app_data.yml
  when: nextcloud_backup_user
- name: Run database backup
  ansible.legacy.import_tasks: database.yml
  when: nextcloud_backup_database
  tags:
    - db_dump
- name: Finish the backup
  ansible.legacy.import_tasks: finishing.yml
- name: Fetch backup to local
  ansible.legacy.import_tasks: fetching.yml
  when: nextcloud_backup_fetch_to_local
