---
- name: Check if host has sudo
  ansible.builtin.command: "dpkg-query -s sudo"
  changed_when: false
  register: __sudo_installed
  failed_when: false

- name: Get nextcloud status
  nextcloud.admin.run_occ:
    nextcloud_path: "{{ nextcloud_webroot }}"
    command: status --output=json
  become: true
  register: _nc_status
  changed_when: false

- name: Get Nextcloud instance ID
  nextcloud.admin.run_occ:
    nextcloud_path: "{{ nextcloud_webroot }}"
    command: config:system:get instanceid
  become: true
  register: _nc_id
  changed_when: false
  when: nextcloud_backup_app_data or nextcloud_backup_user

- name: Find the data folder if required
  when:
  - nextcloud_backup_app_data or nextcloud_backup_user
  - nextcloud_data_dir|d('') == ''
  block:
  - name: Get the data directory
    nextcloud.admin.run_occ:
      nextcloud_path: "{{ nextcloud_webroot }}"
      command: config:system:get datadirectory
    become: true
    register: nc_data_dir
    changed_when: false
  - name: Set missing fact
    ansible.builtin.set_fact:
      nextcloud_data_dir: "{{ nc_data_dir.stdout }}"

- name: Get the list of apps installed
  nextcloud.admin.run_occ:
    nextcloud_path: "{{ nextcloud_webroot }}"
    command: app:list --output=json
  become: true
  register: _nc_app_list
  changed_when: false

- name: Get the list of users
  nextcloud.admin.run_occ:
    nextcloud_path: "{{ nextcloud_webroot }}"
    command: user:list --output=json
  become: true
  register: _nc_user_list
  changed_when: false
  when:
  - nextcloud_backup_user

- name: Find the DB credential if required
  when:
  - nextcloud_backup_database
  become: true
  block:
  - name: Get database type
    nextcloud.admin.run_occ:
      nextcloud_path: "{{ nextcloud_webroot }}"
      command: config:system:get dbtype
    register: _nc_dbtype
    changed_when: false
  - name: Get DB host
    nextcloud.admin.run_occ:
      nextcloud_path: "{{ nextcloud_webroot }}"
      command: config:system:get dbhost
    register: _nc_dbhost
    changed_when: false
  - name: Get DB name
    nextcloud.admin.run_occ:
      nextcloud_path: "{{ nextcloud_webroot }}"
      command: config:system:get dbname
    register: _nc_dbname
    changed_when: false
  - name: Get DB user
    nextcloud.admin.run_occ:
      nextcloud_path: "{{ nextcloud_webroot }}"
      command: config:system:get dbuser
    register: _nc_dbuser
    changed_when: false
  - name: Get DB password
    nextcloud.admin.run_occ:
      nextcloud_path: "{{ nextcloud_webroot }}"
      command: config:system:get dbpassword
    register: _nc_dbpassword
    changed_when: false
    no_log: true
