---
- name: "Get the config.php content"
  become: true
  nextcloud.admin.run_occ:
    nextcloud_path: "{{ nextcloud_webroot }}"
    command: config:list
  register: _config_php
  changed_when: _config_php.rc != 0

- name: "Check values inside config.php"
  ansible.builtin.assert:
    that:
      - _config_php.stdout is regex('\"mysql\.utf8mb4\"[:] true,')
    success_msg: "All regular expressions/searches passed."
    fail_msg: "At least one check for patterns failed."
